[package]
name = "template"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# fancy-regex = "0.13.0"
# regex = "1.10.4"
# md-5 = "0.10.6"
priority-queue = "2.0.2"